version: '3.8'
services:
  # PHP Application
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webdev
    ports:
      - "8080:80"

  # MySQL Database
  mysql-db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "foodorder"
