name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.richadocker03 }} -p ${{ secrets.Docker!123 }}

      - name: Build Docker image
        run: docker build -t richadocker03/FoodOrder:latest .

      - name: Push Docker image to Docker Hub
        run: docker push richadocker03/FoodOrder:latest
